RawEncoder: {}
bn:
  eps: 1.0e-05
  mom: 0.1
cfg_dest: config.yaml
custom_metrics: []
dataset:
  augment_feature: []
  augment_feature_dims: []
  augment_feature_repr: original
  augment_label: ''
  augment_label_dims: 0
  cache_load: false
  cache_save: false
  dir: /nobackup/users/junhong/Data
  edge_dim: 128
  edge_encoder: false
  edge_encoder_bn: true
  edge_encoder_name: Bond
  edge_encoder_num_types: 4
  edge_message_ratio: 0.8
  edge_negative_sampling_ratio: 1.0
  edge_train_mode: all
  encoder: true
  encoder_bn: true
  encoder_dim: 128
  encoder_name: db
  format: OGB
  hop: 3
  infer_link_label: None
  label_column: none
  label_table: none
  location: local
  name: ogbg-molhiv
  node_encoder: true
  node_encoder_bn: true
  node_encoder_name: Atom
  node_encoder_num_types: 100
  preprocess: None
  rand_split: false
  remove_feature: false
  resample_disjoint: false
  resample_negative: false
  shuffle_split: true
  slic_compactness: 10
  split:
  - 0.8
  - 0.1
  - 0.1
  split_dir: ./splits
  split_index: 0
  split_mode: standard
  task: graph
  task_entity: ''
  task_type: classification
  to_undirected: false
  transductive: false
  transform: none
  tu_simple: true
device: auto
gnn:
  A_embed: true
  K: 10
  act: relu
  agg: mean
  alpha: 0.1
  attn_dropout: 0.0
  attn_final_linear: false
  attn_final_linear_bn: false
  attn_heads: 1
  batch_norm: false
  batchnorm: true
  clear_feature: true
  dim_inner: 80
  dropout: 0.0
  flow: source_to_target
  head: graphormer_graph
  hops: 7
  input_dropout: 0.0
  jumping_knowledge: false
  keep_edge: 0.5
  l2norm: true
  layer_norm: false
  layer_type: generalconv
  layers_mp: 2
  layers_post_mp: 3
  layers_pre_mp: 0
  msg_direction: single
  normalize_adj: false
  output_l2_norm: false
  residual: true
  self_msg: concat
  skip_every: 1
  stage_type: stack
  use_linear: false
gpu_mem: false
gt:
  act: relu
  attn_dropout: 0.1
  attn_heads: 8
  attn_type: GeneralAttention
  batch_norm: false
  dim_hidden: 80
  dropout: 0.1
  edge_encoder_list:
  - TypeDictEdge
  ffn_dim: 0
  full_graph: true
  gamma: 1.0e-05
  head: class_graph
  input_dropout: 0.1
  l2_norm: false
  layer_norm: true
  layer_type: SANLayer
  layers: 12
  node_encoder_list:
  - TypeDictNode+GraphormerBias
  pna_degrees: []
  prepend_norm: true
  residual: true
  use_graph_token: false
  virtual_nodes: 0
mask:
  name: full
mem:
  inplace: false
metric_agg: argmax
metric_best: rocauc
model:
  edge_decoding: dot
  graph_pooling: graph_token
  loss_fun: bce
  loss_fun_weight: []
  match_upper: true
  size_average: mean
  thresh: 0.5
  type: GTModel
name_tag: ''
num_threads: 6
num_workers: 0
optim:
  base_lr: 0.001
  batch_accumulation: 1
  clip_grad_norm: true
  clip_grad_norm_value: 5.0
  lr_decay: 0.1
  max_epoch: 2
  min_lr: 0.0
  momentum: 0.9
  num_warmup_epochs: 50
  optimizer: adamW
  reduce_factor: 0.1
  schedule_patience: 10
  scheduler: polynomial_with_warmup
  steps:
  - 30
  - 60
  - 90
  weight_decay: 0.01
out_dir: results_molhiv/Graphormer
posenc_ElstaticSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: range(10)
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_EquivStableLapPE:
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  raw_norm_type: none
posenc_GraphormerBias:
  dim_pe: 16
  enable: true
  enable_path_bias: true
  layers: 3
  model: none
  multi_hop_max_dist: 5
  n_heads: 4
  node_degrees_only: false
  num_in_degrees: 64
  num_out_degrees: 64
  num_spatial_types: 20
  pass_as_var: false
  path_edge_feat_dim: 4
  post_layers: 0
  raw_norm_type: none
posenc_HKdiagSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_ComplEx:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_DistMult:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_GNN:
  act: relu
  agg: mean
  attn_dropout: 0.0
  batch_norm: false
  dim_pe: 16
  dropout: 0.0
  enable: false
  input_dropout: 0.0
  layer_norm: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  pre_layers: 0
  raw_norm_type: none
posenc_Hetero_Label:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_Metapath:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_Node2Vec:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_RWSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_SDAB:
  dim_pe: 0
  enable: false
  enable_path: false
  node_degrees_only: false
  num_spatial_types: 0
posenc_Hetero_SDPE:
  dim_pe: 0
  enable: false
  num_spatial_types: 0
posenc_Hetero_TransE:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_kHopAB:
  dim_pe: 0
  enable: false
  num_spatial_types: 0
posenc_Hetero_kHopAug:
  dim_pe: 0
  enable: false
  num_spatial_types: 0
posenc_Homo_GNN:
  act: relu
  agg: mean
  attn_dropout: 0.0
  batch_norm: false
  dim_pe: 16
  dropout: 0.0
  enable: false
  input_dropout: 0.0
  layer_norm: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  pre_layers: 0
  raw_norm_type: none
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_RWSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_SignNet:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  phi_hidden_dim: 64
  phi_out_dim: 4
  post_layers: 0
  raw_norm_type: none
pretrained:
  dir: ''
  freeze_main: false
  reset_prediction_head: true
print: both
round: 5
run_dir: results_molhiv
run_multiple_splits: []
seed: 0
share:
  dim_in: 1
  dim_out: 1
  num_splits: 1
tensorboard_agg: true
tensorboard_each_run: false
train:
  ans_weight_update: 10000
  auto_resume: false
  batch_size: 256
  ckpt_best: false
  ckpt_clean: true
  ckpt_period: 100
  enable_ckpt: true
  epoch_resume: -1
  eval_period: 1
  iter_per_epoch: 0
  mode: custom
  neighbor_sizes:
  - 20
  - 15
  - 10
  - 5
  neighbor_sizes_dict: ''
  node_per_graph: 32
  num_parts: 10
  persistent_workers: true
  pin_memory: true
  radius: extend
  sample_node: false
  sampler: full
  skip_train_eval: false
  tqdm: true
  walk_length: 4
val:
  iter_per_epoch: 0
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
  tqdm: false
view_emb: false
