out_dir: ./results/zinc
metric_best: mae
metric_agg: argmin
seed: 42
dataset:
  dir: /mnt/data2/duxin/.datasets
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
num_threads: 24
num_workers: 18
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 256
  eval_period: 4
  ckpt_period: 100
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  tqdm: True
model:
  type: GTModel
  loss_fun: l1
gt:
  node_encoder_list: ['TypeDictNode']
  edge_encoder_list: ['TypeDictEdge']
  attn_type: GeneralAttention
  layers: 10
  attn_heads: 8
  dim_hidden: 256  
  dropout: 0.2     # global transformer dropout
  attn_dropout: 0.2
  batch_norm: False
  layer_norm: True
  residual: True
  head: san_graph
gnn:
  dropout: 0.2
optim:
  batch_accumulation: 32
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5