out_dir: ./results/Graphormer
metric_best: accuracy
seed: 48
dataset:
  dir: /mnt/data2/duxin/.datasets
  format: OGB
  name: ogbn_arxiv
  task: node
  task_type: classification
  task_entity: item
  transductive: True
num_threads: 24
num_workers: 16
train:
  mode: custom
  sampler: neighbor
  neighbor_sizes: [3,2] 
  iter_per_epoch: -1
  batch_size: 64
  eval_period: 4
  ckpt_period: 100
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  sampler: neighbor
  iter_per_epoch: -1
  tqdm: True
model:
  type: Graphormer
  loss_fun: cross_entropy
gt:
  layer_type: GraphormerLayer
  attn_type: TorchFullAttention
  layers: 18
  dim_hidden: 1024
  dropout: 0.1    
  attn_dropout: 0.3
  ffn_dim: 1024
  attn_heads: 8
  use_graph_token: False
  input_dropout: 0.0
gnn:
  dropout: 0.2
optim:
  batch_accumulation: 32
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 5
  scheduler: polynomial_with_warmup
  num_warmup_epochs: 5
posenc_GraphormerBias: 
  enable: True
  max_dist: 4
  num_in_degrees: 26
  num_out_degrees: 14
  node_degrees_only: False