out_dir: ./results/test
metric_agg: argmax
metric_best: accuracy
num_workers: 8
seed: 0

dataset:
  dir: /mnt/data2/duxin/.datasets
  format: OGB
  name: ogbn-arxiv
  split_mode: standard
  task: node
  task_type: classification
  task_entity: item
  transductive: false
  add_self_loops: True
  num_virt_node: 0
  rb_order: 2

train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  batch_size: 128
  tqdm: True
  sampler: neighbor
  persistent_workers: True
  pin_memory: True
  neighbor_sizes: [25,10]

val:
  sampler: neighbor
  iter_per_epoch: -1
  tqdm: True

model:
  type: GTModel
  loss_fun: cross_entropy

gnn:
  mode: "off"
  dropout: 0.3
  act: relu
  batch_norm: true
  dim_inner: 80
  layers_pre_mp: 1
  layers_post_mp: 1
  normalize_adj: false

gt:
  attn_dropout: 0.167
  batch_norm: false
  dim_hidden: 128
  dropout: 0.612
  layer_norm: false
  layer_type: NodeFormerConv
  attn_type: LinearAttn
  layers: 2
  attn_heads: 8
  ffn_dim: 80
  head: inductive_node
  encoder_type: cascade
  node_encoder_list: []
  edge_encoder_list: [DummyEdge]

  # === NodeFormer-specific ===
  edge_loss_weight: 0.1
  graph_weight: 0.8
  kernel_trans: "softmax"
  nb_random_features: 30
  rb_order: 2
  rb_trans: "sigmoid"
  use_act: True
  use_edge_loss: True
  use_gumbel: True

optim:
  base_lr: 0.003
  clip_grad_norm: true
  clip_grad_norm_value: 0.329
  max_epoch: 600
  num_warmup_epochs: 5
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 1e-4

perf:
  mode: "off"
