out_dir: ./results/test
metric_agg: argmax
metric_best: accuracy
dataset:
  dir: /mnt/data2/duxin/.datasets
  format: OGB
  name: ogbn-arxiv
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
  num_virt_node: 0
  rb_order: 2
train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  batch_size: 1
  sampler: full_batch
  ckpt_period: 100
gnn:
  mode: "off"
  layer_type: GCN
  act: relu
  agg: add
  batch_norm: true
  dim_inner: 80
  dropout: 0.3
  layers_post_mp: 1
  layers_pre_mp: 1
  normalize_adj: false

gt:
  attn_dropout: 0.5
  batch_norm: true
  dim_hidden: 80
  dropout: 0.3
  layer_norm: false
  layer_type: NodeFormerConv
  attn_type: LinearAttn
  layers: 4
  attn_heads: 2
  ffn_dim: 160
  head: inductive_node
  encoder_type : cascade
  node_encoder_list: []
  edge_encoder_list: [DummyEdge]

  edge_loss_weight: 0.1
  graph_weight: 0.8
  kernel_trans: "softmax"
  nb_random_features: 30
  rb_order: 2
  rb_trans: "sigmoid"
  use_act: True
  use_edge_loss: True
  use_gumbel: True

model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: GTModel
optim:
  base_lr: 0.003
  clip_grad_norm: true
  max_epoch: 400
  num_warmup_epochs: 5
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 5e-4
perf:
  mode: "off"
